#import "../Phys4AI_definitions.typ": *

The *electrostatic force* is one of the four fundamental forces that
govern the physical world. Many forces, like friction or the normal
force, are actually electrostatic forces in disguise. At fine-grain
level, electrostatic forces can be explained in terms of interactions
between the elementary constituents of matter, protons and electrons.
However, it's entirely possible to approach such forces, at least as
a starting point, in terms of forces and fields, in the same way as
gravity #footnote[Indeed, the atomic model (protons and neutrons in
the nucleus with electrons orbiting around) came much further in time
than the formal treatment of electrostatic forces.].

First, it is a known empirical fact that rubbing certain objects
together render them capable of pushing or pulling other objects.
For example, rubbing a plastic stick with a piece of wool cloth
makes the stick, for a short period of time, capable of pulling
towards itself small bits of paper. Also, by rubbing two plastic
sticks with a piece of wool cloth and placing them side by side,
the two sticks push each other away. Interestingly, when a plastic
stick rubbed with a piece of wool cloth is placed side by side with
a glass stick rubbed with a piece of silk cloth, the two are drawn
closer to each other.

This pushing and pulling, when understood in terms of forces, are
defined as the electrostatic force. This force seems to be "induced"
by applying friction between two specific materials. When an object
acquires the capability of pushing or pulling other objects, it is
said to be *electrically charged*, or just *charged* for short. An
object that is not charged is said to be *neutral*.

This charge has to exist in (at least) two flavours, since two rubbed
plastic rods push each other away but a rubbed plastic stick and a rubbed
glass stick pull each other closer. Actually, no experiment has ever found
a third flavour of charge: there is no object that, when charged, is capable
of pushing or pulling both rods. That is, it always pushes one and pulls the
other.

These two flavours are called *positive charge* and *negative charge*: said
names are essentially arbitrary (if, from now on, positive charges were to
be defined to be negative charges or vice versa, nothing would change), but
they hint at the fact that an equal amount of positive charge and an equal
amount of negative charge cancel out, like two numbers equal in magnitude
but opposite in sign.

One is to be careful in the definition of a charged object and a neutral
object. Indeed, a charged object pulls a neutral object onto itself, but
the phenomena could also be interpreted as the neutral object pulling the
charged object onto itself. The difference lies in the fact that a charged
object both pulls neutral objects and objects having the opposite charge,
while pushing objects with the same charge a neutral. On the other hand,
a neutral object pulls both charges but does nothing with other neutral
objects.

Non-rubbed rods cannot pull bits of paper towards themselves, but rubbed
rods can. Also, the rubbed rod and the piece of cloth used to rub it are
drawn close to each other. This must mean that both the rod and the cloth,
initally neutral, already possessed said charge, but in equal amount of
both flavours: after rubbing, an "imbalance" is created, with both objects
acquiring charge but of opposite flavours.

As the necessity of friction suggests, electric charge is generated by
contact. However, not all objects "retain" charge; some objects, when
charged, keep the charge for themselves, others let charge pass through
them. The first kind of objects are called *insulators*, the second
*conductors*.

Even though the charge model is sufficient to explain electromagnetic
force, a deeper look into the fine structure of matter reveals its
origin. In particular, the charge of objects is to be found in their
atoms: each atom is constituted by even smaller costituens, called
*particles*. Said particles come in three flavours: *protons*, *neutrons*
and *electrons*. Each atom has a mixture of *protons* and *neutrons*
tightly bound together at its center, called the *nucleus*, and the
electrons orbit around said nucleus.

Each proton, neutron and electron in every atom of the Universe has a
precise definite mass and a precise definite amount of charge. This
charge, just like mass, is a property intrinsic to the particle, and
cannot be altered in any way. Any proton has the exact same amount
of charge as any electron, but of distinct kind, while neutrons have
charge equal to $0$. By convention, protons are assigned the positive
charge and electrons the negative charge. The attractive electric force
between the positive protons and the negative electrons is what keeps
the atom in place.

The amount of charge of a single electron is denoted with $-e$, while
the charge of a single proton is denoted by $+e$: the plus and minus
sign refer to the fact that said charges are assigned to be the negative
and the positive charge, respectively. To refer to the magnitude of the
charge without referring to its sign, the symbol $e$ is used. The charge
of an atom, denoted with $q$ is therefore:

$ q = e dot ("number of its protons" - "number of its electrons") $

Since most atoms have the exact same amount of protons and electrons,
their net amount of charge is $0$, because the positive and negative
charges even out. 

The charge $e$ is called the *elementary charge*, because electrons and
protons are the smallest objects in existence that have an electric charge,
and it's not possible to split them apart further #footnote[Actually, this
is only true for electrons. Protons are in turn constituted by even smaller
particles, called *quarks*, whose elementary charge result in a net charge
of $+e$. In particular, a proton consists of two quarks with charge $+2
slash 3 e$, called *up quarks* and one quark with charge $-1 slash 3$,
called *down quark*. Treating the protons as indivisible units is still
better, however, both because it is simpler and because single, isolated
quarks do not exist in nature.]. This also means that electric charge is
*quantized*, meaning that the charge of a large object (made of two or
more atoms) is the sum of the charges of each of its atoms, and is therefore
an integer multiple of $e$.

An atom, to be charged, must therefore have more protons than electrons
or more electrons than protons. The protons of an atom is tightly bound
to the nucleus, therefore it is almost impossible for an atom to "lose"
or "acquire" a proton. It is however much more likely for an atom to
"lose" or "acquire" an electron. This is because the electron is loosely
bound to the nucleus, and a sufficient force (like the friction between
a rod and a piece of cloth) can overcome this force, moving said electrons
from an atom to another.

The process of removing an electron from an atom is called *ionization*.
Ionization creates two atoms where one is in defect of one or more
electrons, and is therefore positively charged, and the other has a
surplus of one or more electrons, and is therefore negatively charged.
The first is also called *positive ion*, the second *negative ion*. Note
that charge is *conserved*: if an atom gains a certain amount of positive
charge, another atom has to lose the exact same amount of positive charge
and the same holds for negative charge. No charge can be created out of
nothing or disappear.

The atomic structure also explains why some materials are conductors and
some others are insulators. Insulators are materials whose electrons are
very tightly bound to their nucleus, whereas conductors are materials
whose electrons are very loosely coupled. Even when a conductor has no
charge, its electrons are so loose that they almost "drift around" its
volume a single, defined atom to which they belong. This means that when
electrons are added or subtracted from a conductor, the electric imbalance
spreads out quickly. On the other hand, when a conductor is positively or
negatively charged, such charging remains localized.

// Much more content is missing, such as how to charge, polarization, ecc...

The charge of an object is measured in *Coulomb* (symbol $coulomb$); the
fundamental charge is equal to:

$ e = num(1.60E-19) coulomb $

The electrostatic force that exists between two charged objects can
quantified by a formula, known as *Coulomb's Law*:

$ F_(1 "on" 2) = F_(2 "on" 1) = frac(1, 4 pi epsilon_(0)) frac(abs(q_(1)) abs(q_(2)), r^(2)) $

Where $q_(1)$ and $q_(2)$ are the charges of the two particles, $r$ is
the distance between them and $epsilon_(0)$ is a constant, known as
*permittivity constant*. Its value is:

$ epsilon_(0) = num(8.85E-12) coulomb^(2) slash newton metre^(2) $

Since $4 pi$ is itself constant, the expression $1 slash 4 pi epsilon_(0)$
is itself a constant, called the *electrostatic constant*. Said constant
is sometimes written as $K$, whose value is:

$ K = num(8.99E+9) newton metre^(2) slash coulomb^(2) $

The electrostatic forces are directed along the line joining the two
particles: they are repulsive for two charges of the same sign and
attractive for two charges of opposite sign.

#figure(
	caption: [On the left, two positive electric charges push each other
	          away, since their charge is of the same sign. On the right,
	          two negative electric charges push each other away for the
	          same reason. In the middle, a positive and a negative electric
	          charge are drawn closer to each other, since their charge is
	          of the same sign.],
	[#grid(
		columns: (0.33fr, 0.33fr, 0.33fr),
		[#cetz.canvas({
			import cetz.draw: *
			set-style(
				content: (padding: 3pt),
				stroke: (thickness: 1.25pt),
			)

			circle((0, -1), radius: 0.375, name: "q1", fill: rgb("#ffacab"), stroke: (paint: red))
			circle((2, 1), radius: 0.375, name: "q2", fill: rgb("#ffacab"), stroke: (paint: red))
			content("q1", text(size: 20pt, fill: red, [+]))
			content("q2", text(size: 20pt, fill: red, [+]))
			content("q1", $q_(1)$, anchor: "south-east", padding: 0.3)
			content("q2", $q_(2)$, anchor: "north-west", padding: 0.3)
			line("q1", "q2", stroke: (thickness: 0.75pt, dash: "dashed"))
			content(("q1", 50%, "q2"), $r$, angle: "q2", anchor: "south")
			line("q1", (-1, -2), mark: (end: "stealth"), fill: black)
			line("q2", (3, 2), mark: (end: "stealth"), fill: black)
			content((-1, -2), $arrow(F)_(2 "on" 1)$, anchor: "north-west")
			content((3, 2), $arrow(F)_(1 "on" 2)$, anchor: "south-east")
		})],
		[#cetz.canvas({
			import cetz.draw: *
			set-style(
				content: (padding: 3pt),
				stroke: (thickness: 1.25pt),
			)

			circle((-0.5, -1.5), radius: 0.375, name: "q1", fill: rgb("#ffacab"), stroke: (paint: red))
			circle((2.5, 1.5), radius: 0.375, name: "q2", fill: aqua, stroke: (paint: blue))
			content("q1", text(size: 20pt, fill: red, [+]))
			content("q2", text(size: 20pt, fill: blue, [-]))
			content("q1", $q_(1)$, anchor: "south-east", padding: 0.3)
			content("q2", $q_(2)$, anchor: "north-west", padding: 0.3)
			line("q1", "q2", stroke: (thickness: 0.75pt, dash: "dashed"))
			content(("q1", 50%, "q2"), $r$, angle: "q2", anchor: "south")
			line("q1", (0.5, -0.5), mark: (end: "stealth"), fill: black)
			line("q2", (1.5, 0.5), mark: (end: "stealth"), fill: black)
			content((0.5, -0.5), $arrow(F)_(2 "on" 1)$, anchor: "south-east")
			content((1.5, 0.5), $arrow(F)_(1 "on" 2)$, anchor: "north-west")
		})],
		[#cetz.canvas({
			import cetz.draw: *
			set-style(
				content: (padding: 3pt),
				stroke: (thickness: 1.25pt),
			)

			circle((0, -1), radius: 0.375, name: "q1", fill: aqua, stroke: (paint: blue))
			circle((2, 1), radius: 0.375, name: "q2", fill: aqua, stroke: (paint: blue))
			content("q1", text(size: 20pt, fill: blue, [-]))
			content("q2", text(size: 20pt, fill: blue, [-]))
			content("q1", $q_(1)$, anchor: "south-east", padding: 0.3)
			content("q2", $q_(2)$, anchor: "north-west", padding: 0.3)
			line("q1", "q2", stroke: (thickness: 0.75pt, dash: "dashed"))
			content(("q1", 50%, "q2"), $r$, angle: "q2", anchor: "south")
			line("q1", (-1, -2), mark: (end: "stealth"), fill: black)
			line("q2", (3, 2), mark: (end: "stealth"), fill: black)
			content((-1, -2), $arrow(F)_(2 "on" 1)$, anchor: "north-west")
			content((3, 2), $arrow(F)_(1 "on" 2)$, anchor: "south-east")
		})]
	)]
)

Coulomb's Law is very similar to Newton's Law for gravity: both have
the two properties of the object at the numerator multiplied together,
both are proportional to a constant and both have the distance between
the two particles as their denominator. Also, both laws work assuming
that the objects are point-like, meaning that their other properties
(mass, volume, shape, ecc...) are negligible with respect to their
reciprocal distance.

However, while gravity is always an attractive force, electrostatic
force exists both in an attractive and in a repulsive fashion. Also,
the gravitational constant $G$ is much (much) smaller than the
electrostatic constant $K$, meaning that charges and masses of
the same order of magnitude, the electrostatic force is incredibly
stronger than gravity.

#exercise[
	The mass of a proton is $num(1.67E-27) kilo gram$, while the mass
	of an electron is $num(9.11E-31) kilo gram$. What is the ratio
	between the gravitational force between an electron and a proton
	and the electrostatic force between an electron and a proton that
	are $1 metre$ apart? Assume an electron 
]
#solution[
	$ F_(e) &= frac(1, 4 pi dot num(8.85E-12) coulomb^(2) slash newton metre^(2))
	          (frac(abs(num(1.60E-19) coulomb) dot abs(num(1.60E-19) coulomb), 1 metre^(2)))
	        = num(2.30E-28) newton \
	  F_(g) &= num(6.67E-11) metre^(3) kilo gram^(-1) s^(-2)
	          (frac(num(1.67E-27) kilo gram dot num(9.11E-31) kilo gram, 1 metre^(2)))
			= num(1.01E-67) newton $

	Which means that the electrostatic force between the two is greater
	than the gravitational force between the two by a factor of:

	$ frac(F_(e), F_(g)) =
	  frac(num(2.30E-28) newton, num(1.01E-67) newton) approx
	  num(2.27E+39) $
]

Electrostatic force is no different than any other force, therefore
the superposition principle holds: the net electrostatic force in a
system is given by the sum of the electrostatic forces of the single
components. Superposition also holds between a mixture of electrostatic
and gravitational forces.

#exercise[
	Three charges $q_(1), q_(2), q_(3)$ are arranged in a triangle at the
	following coordinates: $(0.0 centi metre, 0.0 centi metre)$, $(5.0 centi
	metre, 0.0 centi metre)$, $(0,0 centi metre, 10.0 centi metre)$. Their
	charges are, respectively: $q_(1) = -50 nano coulomb$, $q_(2) = +50
	nano coulomb$, $q_(3) = +30 nano coulomb$. What is the net force
	acting upon the third charge?
]
#solution[
	Since (electrostatic) forces can be superimposed, the resulting force
	acting upon the third charge is the vector sum between the force coming
	from the first charge and the force coming from the second charge.

	The distance from the second charge to the third charge can be obtained
	by applying Pythagoras' Theorem:

	$ r_(2, 3) =
	  sqrt(r_(1, 3)^(2) + r_(1, 2)^(2)) = 
	  sqrt((5.0 centi metre)^(2) + (10.0 centi metre)^(2)) = 
	  sqrt(125.0 centi metre^(2)) approx
	  11.2 centi metre $

	The magnitude of the force acting on the third charge from the first
	charge is given by:

	$ F_(1 "on" 3) = frac(1, 4 pi dot num(8.85E-12) coulomb^(2) slash newton metre^(2))
	        (frac(abs(num(+30E-9) coulomb) dot abs(num(-50E-9) coulomb), 0.100 metre^(2))) =
	        num(+1.35E-3) newton $

	The magnitude of the force acting on the third charge from the second
	charge is given by:

	$ F_(2 "on" 3) = frac(1, 4 pi dot num(8.85E-12) coulomb^(2) slash newton metre^(2))
	        (frac(abs(num(+30E-9) coulomb) dot abs(num(+50E-9) coulomb), 0.112 metre^(2))) =
	        num(+1.08E-3) newton $

	Consider a system of coordinates centered on the third charge. The
	force $arrow(F)_(1 "on" 3)$ points downward, hence has no component
	on the $x$-axis and its $y$-component is negative. The force
	$arrow(F)_(2 "on" 3)$ points north-west, hence has both an $x$ and
	a $y$ component. The angle $theta$ between $arrow(F)_(2 "on" 3)$
	and the coordinate system is:

	$ theta =
	  arctan(frac("opposite side", "adjacent side")) =
	  arctan(frac(10.0 centi metre, 5.0 centi metre)) =
	  arctan(2.0) approx 63.4 degree $

	Which means that the two components of $arrow(F)_(2 "on" 3)$ along the
	$x$ and $y$ axis are:

	$ F_(2 "on" 3, x) &= cos(theta) F_(2, "on" 3) = cos(63.4 degree) num(+1.08E-3) newton = num(+4.83E-4) newton \
	  F_(2 "on" 3, y) &= sin(theta) F_(2, "on" 3) = sin(63.4 degree) num(+1.08E-3) newton = num(+9.66E-4) newton $

	The net force along the $x$ axis is just $F_(2 "on" 3, x)$, since
	$F_(1 "on" 3)$ has no component in this direction. The net force
	along the $y$ axis is:

	$ F_(3, y) =
	  abs(F_(2 "on" 3, y) - F_(1 "on" 3)) =
	  abs(num(+9.66E-4) newton - num(+1.35E-3) newton) =
	  num(+3.84E-4) newton $

	Where the minus sign hints at the fact that the two forces point
	in opposite directions. The magnitude of the resulting force is
	therefore:

	$ F_(3) = sqrt(F_(3, x)^(2) + F_(3, y)^(2)) =
	  sqrt((num(+4.83E-4) newton)^(2) + (num(+3.84E-4) newton)^(2))
	  = num(+6.20E-4) newton $

	The $x$ component of $F_(3)$ points leftwards, since $F_(2 "on" 3, x)$
	points leftward. The $y$ component of $F_(3)$ points downwards, since
	$F_(1 "on" 3)$ is greater in magnitude than $F_(2 "on" 3, y)$.
	Therefore, $F_(3)$ points south-west. In particular, the angle between
	$F_(3)$ and the $x$ axis is:

	$ phi.alt =
	  arctan(frac("opposite side", "adjacent side")) =
	  arctan(frac(num(+3.84E-4) newton, num(+4.83E-4) newton)) =
	  arctan(0.79) approx 38.5 degree $

	#figure(
		caption: [On the left, a graphical representation of the disposition
		          of the three charges. On the right, the forces acting upon
		          the $q_(3)$ charge.],
		[#grid(
			columns: (0.5fr, 0.5fr),
			[#cetz.canvas({
				import cetz.draw: *
				set-style(
					content: (padding: 3pt),
					stroke: (thickness: 1.25pt),
				)

				circle((0, 0), radius: 0.375, name: "q1", fill: aqua, stroke: (paint: blue))
				circle((2.5, 0), radius: 0.375, name: "q2", fill: rgb("#ffacab"), stroke: (paint: red))
				circle((0, 5), radius: 0.375, name: "q3", fill: rgb("#ffacab"), stroke: (paint: red))
				content("q1", text(size: 20pt, fill: blue, [-]))
				content("q2", text(size: 20pt, fill: red, [+]))
				content("q3", text(size: 20pt, fill: red, [+]))
				line("q1", "q2", stroke: (dash: "dashed"))
				line("q2", "q3", stroke: (dash: "dashed"))
				line("q1", "q3", stroke: (dash: "dashed"))

				content("q1", $q_(1) = -50 nano coulomb$, anchor: "north-east", padding: 0.4)
				content("q2", $q_(2) = +50 nano coulomb$, anchor: "north-west", padding: 0.4)
				content("q3", $q_(3) = +30 nano coulomb$, anchor: "south-east", padding: 0.4)

				content(("q1", 50%, "q2"), $5.0 centi metre$, anchor: "north")
				content(("q2", 50%, "q3"), $11.2 centi metre$, angle: "q2", anchor: "south")
				content(("q1", 50%, "q3"), $10.0 centi metre$, angle: "q3", anchor: "south")
			})],
			[#cetz.canvas({
				import cetz.draw: *
				set-style(
					stroke: (thickness: 1.5pt),
					padding: 0.1
				)

				line((0, 0), (0, 2), mark: (end: "stealth"), stroke: (paint: red, dash: "dashed"), fill: red)
				line((0, 0), (-1, 0), mark: (end: "stealth"), stroke: (paint: red, dash: "dashed"), fill: red)
				line((0, 0), (-1, 2), mark: (end: "stealth"), stroke: (paint: red), fill: red)
				line((0, 0), (0, -2.875), mark: (end: "stealth"), stroke: (paint: blue), fill: blue)
				line((0, 0), (-1, -0.875), mark: (end: "stealth"), stroke: (paint: black), fill: black)
				line((-1, 2), (-1, -0.875), (0, -2.875), stroke: (dash: "dashed"))
				circle((0, 0), fill: white, radius: 0.1)

				content((0, -2.875), $F_(1 "on" 3)$, anchor: "north")
				content((-1, 2), $F_(2 "on" 3)$, anchor: "south-east")
				content((-1, 0), $F_(2 "on" 3, x)$, anchor: "east")
				content((0, 2), $F_(2 "on" 3, y)$, anchor: "south")
				content((-1, -0.875), $F_(3)$, anchor: "north-east")
				content((0, 0), $q_(3)$, anchor: "north-west")
				content((-0.375, 0.25), $theta$)
				content((-0.625, -0.25), $phi.alt$)
			})],
		)]
	)
]
