#import "../Phys4AI_definitions.typ": *

The *electrostatic force* is one of the four fundamental forces that
govern the physical world. Many forces, like friction or the normal
force, are actually electrostatic forces in disguise. At fine-grain
level, electrostatic forces can be explained in terms of interactions
between the elementary constituents of matter, protons and electrons.
However, it's entirely possible to approach such forces, at least as
a starting point, in terms of forces and fields, in the same way as
gravity #footnote[Indeed, the atomic model (protons and neutrons in
the nucleus with electrons orbiting around) came much further in time
than the formal treatment of electrostatic forces.].

First, it is a known empirical fact that rubbing certain objects
together render them capable of pushing or pulling other objects.
For example, rubbing a plastic stick with a piece of wool cloth
makes the stick, for a short period of time, capable of pulling
towards itself small bits of paper. Also, by rubbing two plastic
sticks with a piece of wool cloth and placing them side by side,
the two sticks push each other away. Interestingly, when a plastic
stick rubbed with a piece of wool cloth is placed side by side with
a glass stick rubbed with a piece of silk cloth, the two are drawn
closer to each other.

This pushing and pulling, when understood in terms of forces, are
defined as the electrostatic force. This force seems to be "induced"
by applying friction between two specific materials. When an object
acquires the capability of pushing or pulling other objects, it is
said to be *electrically charged*, or just *charged* for short. An
object that is not charged is said to be *neutral*.

This charge has to exist in (at least) two flavours, since two rubbed
plastic rods push each other away but a rubbed plastic stick and a rubbed
glass stick pull each other closer. Actually, no experiment has ever found
a third flavour of charge: there is no object that, when charged, is capable
of pushing or pulling both rods. That is, it always pushes one and pulls the
other.

These two flavours are called *positive charge* and *negative charge*: said
names are essentially arbitrary (if, from now on, positive charges were to
be defined to be negative charges or vice versa, nothing would change), but
they hint at the fact that an equal amount of positive charge and an equal
amount of negative charge cancel out, like two numbers equal in magnitude
but opposite in sign.

One is to be careful in the definition of a charged object and a neutral
object. Indeed, a charged object pulls a neutral object onto itself, but
the phenomena could also be interpreted as the neutral object pulling the
charged object onto itself. The difference lies in the fact that a charged
object both pulls neutral objects and objects having the opposite charge,
while pushing objects with the same charge a neutral. On the other hand,
a neutral object pulls both charges but does nothing with other neutral
objects.

Non-rubbed rods cannot pull bits of paper towards themselves, but rubbed
rods can. Also, the rubbed rod and the piece of cloth used to rub it are
drawn close to each other. This must mean that both the rod and the cloth,
initally neutral, already possessed said charge, but in equal amount of
both flavours: after rubbing, an "imbalance" is created, with both objects
acquiring charge but of opposite flavours.

As the necessity of friction suggests, electric charge is generated by
contact. However, not all objects "retain" charge; some objects, when
charged, keep the charge for themselves, others let charge pass through
them. The first kind of objects are called *insulators*, the second
*conductors*.

Even though the charge model is sufficient to explain electromagnetic
force, a deeper look into the fine structure of matter reveals its
origin. In particular, the charge of objects is to be found in their
atoms: each atom is constituted by even smaller costituens, called
*particles*. Said particles come in three flavours: *protons*, *neutrons*
and *electrons*. Each atom has a mixture of *protons* and *neutrons*
tightly bound together at its center, called the *nucleus*, and the
electrons orbit around said nucleus.

Each proton, neutron and electron in every atom of the Universe has a
precise definite mass and a precise definite amount of charge. This
charge, just like mass, is a property intrinsic to the particle, and
cannot be altered in any way. Any proton has the exact same amount
of charge as any electron, but of distinct kind, while neutrons have
charge equal to $0$. By convention, protons are assigned the positive
charge and electrons the negative charge. The attractive electric force
between the positive protons and the negative electrons is what keeps
the atom in place.

The amount of charge of a single electron is denoted with $-e$, while
the charge of a single proton is denoted by $+e$: the plus and minus
sign refer to the fact that said charges are assigned to be the negative
and the positive charge, respectively. To refer to the magnitude of the
charge without referring to its sign, the symbol $e$ is used. The charge
of an atom, denoted with $q$ is therefore:

$ q = e dot ("number of its protons" - "number of its electrons") $

Since most atoms have the exact same amount of protons and electrons,
their net amount of charge is $0$, because the positive and negative
charges even out. 

The charge $e$ is called the *elementary charge*, because electrons and
protons are the smallest objects in existence that have an electric charge,
and it's not possible to split them apart further #footnote[Actually, this
is only true for electrons. Protons are in turn constituted by even smaller
particles, called *quarks*, whose elementary charge result in a net charge
of $+e$. In particular, a proton consists of two quarks with charge $+2
slash 3 e$, called *up quarks* and one quark with charge $-1 slash 3$,
called *down quark*. Treating the protons as indivisible units is still
better, however, both because it is simpler and because single, isolated
quarks do not exist in nature.]. This also means that electric charge is
*quantized*, meaning that the charge of a large object (made of two or
more atoms) is the sum of the charges of each of its atoms, and is therefore
an integer multiple of $e$.

An atom, to be charged, must therefore have more protons than electrons
or more electrons than protons. The protons of an atom is tightly bound
to the nucleus, therefore it is almost impossible for an atom to "lose"
or "acquire" a proton. It is however much more likely for an atom to
"lose" or "acquire" an electron. This is because the electron is loosely
bound to the nucleus, and a sufficient force (like the friction between
a rod and a piece of cloth) can overcome this force, moving said electrons
from an atom to another.

The process of removing an electron from an atom is called *ionization*.
Ionization creates two atoms where one is in defect of one or more
electrons, and is therefore positively charged, and the other has a
surplus of one or more electrons, and is therefore negatively charged.
The first is also called *positive ion*, the second *negative ion*. Note
that charge is *conserved*: if an atom gains a certain amount of positive
charge, another atom has to lose the exact same amount of positive charge
and the same holds for negative charge. No charge can be created out of
nothing or disappear.

The atomic structure also explains why some materials are conductors and
some others are insulators. Insulators are materials whose electrons are
very tightly bound to their nucleus, whereas conductors are materials
whose electrons are very loosely coupled. Even when a conductor has no
charge, its electrons are so loose that they almost "drift around" its
volume a single, defined atom to which they belong. This means that when
electrons are added or subtracted from a conductor, the electric imbalance
spreads out quickly. On the other hand, when a conductor is positively or
negatively charged, such charging remains localized.

// Much more content is missing, such as how to charge, polarization, ecc...
