#import "../Phys4AI_definitions.typ": *

*Electromagnetic waves* are an atypical kind of wave, since they are the
only kind of wave that require no medium to be propagated #footnote[As
touched upon later, matter can also exhibit wave-like properties without
the need for a medium. Matter waves are treated separately from classical
waves, however, since they don't obey the same laws.]: their "waving" are
the self-sustaining oscillations of an *electromagnetic field*. That is,
the displacement $D$ _is_ an electric or magnetic field. This is why, for
example, light (which is a kind of electromagnetic wave) can reach the
Earth from the Sun travelling through nothing but empty space.

It has been predicted theoretically and verified experimentally that all
electromagnetic waves travel through vacuum with the same speed, called
the *speed of light*. The current accepted value of the speed of light,
denoted as $c$, is:

$ c = 299792458 metre slash second approx 3 times 10^(8) metre slash second $

Electromagnetic waves that the human eye can be perceive fall under the
umbrella of *visible light* (or just "light" for short). Visible light
encompasses the electromagnetic waves having wavelength between $700 nano
metre$ to $400 nano metre$; different wavelength in the range are perceived
as different colors. However, there are many more electromagnetic waves
other than visible light, all moving at the speed of light and detectable
by physical apparatuses. These are classified in the following categories:

- *Radio waves*: from $num(1E+4) metre$ to $0.1 metre$, generated by
  charges accelerated in conducting wires (LC circuits) and are used
  mostly in communication;
- *Microwaves*: from $0.3 metre$ to $num(1E-4) metre$, used in radar,
  to study atomic structures, and to cook;
- *Infrared waves*: from $num(1E-3) metre$ to $num(7E-7) metre$,
  produced by molecules and objects at room temperature, absorbed
  by most materials;
- *Visible light*: from $num(7E-7) metre$ to $num(4E-7) metre$,
  part of the electromagnetic spectrum that our eyes can detect;
- *Ultraviolet waves*: from $num(4E-7) metre$ to $num(6E-10) metre$ 
- *X-rays*: from $num(1E-8) metre$ to $num(1E-12) metre$, emitted by
  deceleration of high energetic electrons, and electron transitions;
  in atoms
- *Gamma rays*: from $num(1E-10) metre$ to $num(1E-14) metre$ emitted
  mostly by radioactive decays in unstable nuclei.

The arrangement of all possible frequencies and wavelengths that
electromagnetic waves can have is called the *electromagnetic spectrum*.
Note that the distinction between each class of electromagnetic wave is
purely nominal, since there are no fixed boundaries between one and the
other.

#figure(
	caption: [The electromagnetic spectrum.
	         [#link("https://commons.wikimedia.org/w/index.php?curid=22428451")[Original image]
	         by #link("https://commons.wikimedia.org/wiki/User:Victor_Blacus")[Victor Blacus],
	         licensed under the #link("https://creativecommons.org/licenses/by-sa/3.0/")[CC BY-SA 3.0] license,
	         based on #link("https://commons.wikimedia.org/wiki/File:Electromagnetic-Spectrum.png")[earlier work]
	         by #link("https://commons.wikimedia.org/wiki/User:Penubag")[Penubag]]],
	[#image("EM_spectrum.svg", width: 90%)]
)

Light is, however, even more elusive than the other electromagnetic waves.
This is because treating light merely as a wave is reductive: under different
circumstances, different properties of light emerge. For this reason, it is
important to distinguish between different models of light, each better suited
for describing different phenomena:

- *Light as a wave*. As already stated, light is an electromagnetic wave
  that travels in a vacuum at constant speed $c$. Under many circumstances,
  light behaves no differently than sound or water waves, exhibiting
  superposition and diffraction. Lasers and electro-optical devices are
  best described by interpreting light as being a wave;
- *Light as a ray*. When the wavelengths at play are quite long, light
  travels in bundles of straight lines, as it were a bundle of rays pointing
  in the same direction. The properties of mirrors and lenses, such as
  reflection and refraction, are best understood in terms of light rays.
  The wave interpretation and the ray interpretation are, for the most
  part, mutually exclusive;
- *Light as a particle*. Light can also be understood as a flow of
  quantum objects called *photons*. Photons, possessing both wave-like
  and particle-like properties, arise in treating light from a quantum
  mechanical perspective, such as interpreting the photoelectric effect
  or the black-body radiation.

The basis of the ray model of light is the observation that, in
everyday life experience, light travels in straight lines, or
_rays_, that bounce and/or traverse objects that they encounter.

The ray model is an oversimplification, whose range of validity
is confined to the cases where light traverses apertures (lenses,
mirrors, and holes) that are very large compared to its wavelength.
In this case, light (rays) traverses the aperture without disturbance;
if the aperture is shrunk too much, the passage of light would be
distorted beyond the capabilities of the ray model, and phenomena
such as _diffraction_ would emerge.

A *light ray* is defined as an abstract line (does not represent
any actual, phyisical quantity) emitted from a _source_, moving in
the same direction as the electromagnetic field of light. Any narrow
beam of light, no matter how narrow, is actually a bundle of parallel
light rays close together. *Lasers*, even though still constituted by
many parallel light rays, is as good as an approximation can be of
a single, isolated light ray.

Light rays are represented graphically as, as said, straight lines.
However, the light as a ray model presupposes that light beams are
constituted by an infinite number of rays, hence it is not possible
to draw them all. The idea is to draw only a handful of lines, each
consistent with the way the rays are spreading, restricting the focus
to the lines that are actually worth taking into consideration.

The two main ways light rays are drawn is as rays emitted by a source,
going in every direction, or as a bundle of parallel lines moving in the
same direction. Source-like points make sense when dealing with objects
that are close-by, not only actual light sources but also surfaces that
deflect the incoming light to the surroundings. Parallel rays make sense
when dealing with very precise sources like lasers or when dealing with
far away objects, such as stars, whose incoming light is so distant that
the rays arriving at an observer are essentially parallel to each other.

#figure(
	caption: [A point-like source emitting rays in every direction (left)
	          and a beam-like bundle of parallel rays (right)],
	[#grid(
		columns: (0.5fr, 0.5fr),
		[#cetz.canvas({
			import cetz.draw: *
			set-style(content: (padding: 3pt), stroke: (thickness: 1.5pt))
			line((0, 0), (3, 0), mark: (start: "stealth", end: "stealth"), fill: black)
			line((0.5, 1), (2.5, -1), mark: (start: "stealth", end: "stealth"), fill: black)
			line((1.5, 1.5), (1.5, -1.5), mark: (start: "stealth", end: "stealth"), fill: black)
			line((0.5, -1), (2.5, 1), mark: (start: "stealth", end: "stealth"), fill: black)
		})],
		[#cetz.canvas({
			import cetz.draw: *
			set-style(content: (padding: 3pt), stroke: (thickness: 1.5pt), fill: black)
			line((0, 0), (5, 0), mark: (end: "stealth"))
			line((0, 0.5), (5, 0.5), mark: (end: "stealth"))
			line((0, 1), (5, 1), mark: (end: "stealth"))
			line((0, 1.5), (5, 1.5), mark: (end: "stealth"))
			line((0, 2), (5, 2), mark: (end: "stealth"))
		})]
	)]
)
