#import "../FoundationsQC_definitions.typ": *

#lemma[
  Given two vector spaces $V$ and $W$, let $O$ be an operator
  $O: V -> W$. For any two vectors $bold(v) in V$ and $bold(w)
  in W$, the following holds:

  $ angle.l bold(v), O bold(w) angle.r =
    (angle.l bold(w), bold(v) angle.r)^(dagger) $
]
// #proof[
//
// ]

The *conjugate transpose* of a matrix $A$, denoted as $A^(dagger)$, is the
matrix obtained from transposing $A$ and then applying complex conjugation
to each element of the resulting matrix:

$ A^(dagger) = A^(T^(*)) =
  mat(a_(1, 1), a_(1, 2), dots, a_(1, n);
      a_(2, 1), a_(2, 2), dots, a_(2, n);
      dots.v, dots.v, dots.down, dots.v;
      a_(m, 1), a_(m, 2), dots, a_(m, n))^(T^(*)) =
  mat(a_(1, 1)^(*), a_(2, 1)^(*), dots, a_(m, 1)^(*);
      a_(1, 2)^(*), a_(2, 2)^(*), dots, a_(m, 2)^(*);
      dots.v, dots.v, dots.down, dots.v;
      a_(1, n)^(*), a_(2, n)^(*), dots, a_(m, n)^(*)) $

#exercise[
  What is the conjugate transpose of the following matrix?

  $ A = mat(1, -2 - i, 5;
            1 + i, i, 4 - 2i) $
]
#solution[

  $ A^(dagger) =
    mat(1, -2 - i, 5;
        1 + i, i, 4 - 2i)^(dagger) =
    mat(1, 1 + i;
        -2 - i, i;
        5, 4 - 2i)^(*) =
    mat(1, 1 - i;
        -2 + i, -i;
        5, 4 + 2i) $
]

A square matrix $A$ is said to be *Hermitian* if $A^(dagger) = A$. It
is said to be *unitary* if $A^(dagger) = A^(-1)$.

Any matrix is equivalent to an operator given a fixed basis and vice
versa, therefore it is also possible to define the conjugate transpose
of an operator. Since trasposing an operator in matrix form exchanges
domain and codomain, the conjugate transpose of an operator $O: V -> W$
is the operator $O^(dagger): W -> V$. The matrix representation of
$O^(dagger)$ is, as expected, the conjugate transpose of the matrix
representation of $O$.

#theorem[
  An Hermitian matrix has all real eigenvalues.
]
#proof[
  Let $O: V -> V$ be a linear self-ajoint operator in matrix
  representation, and let $lambda$ be one of its eigenvalues.
  Recall that, given an eigenvector $bold(v) in V$ associated
  to $lambda$, $O bold(v) = lambda bold(v)$. Consider $lambda
  angle.l bold(x), bold(x) angle.r$:

  $ lambda angle.l bold(v), bold(v) angle.r =
    angle.l lambda bold(v), bold(v) angle.r =
    angle.l O bold(v), bold(v) angle.r =
    angle.l bold(v), O^(dagger) bold(v) angle.r =
    angle.l bold(v), O bold(v) angle.r =
    angle.l bold(v), lambda bold(v) angle.r =
    lambda^(*) angle.l bold(v), bold(v) angle.r $

  By definition of eigenvector, $bold(v)$ cannot be the null vector. Also,
  since the inner product between a vector and itself is not null, it is
  allowed to simplify 

  $ lambda cancel(angle.l bold(v)\, bold(v) angle.r) =
    lambda^(*) cancel(angle.l bold(v)\, bold(v) angle.r) =>
    lambda = lambda^(*) $

  Which means that $lambda$ is a real number, because it is equal to its
  complex conjugate.
]

The conjugate transpose of an operator is also called its *adjoint operator*.
If an operator is equal to its adjoint (or equivalently, if its matrix
representation is Hermitian), it is said to be *self-adjoint*. 

Hermitian operators define a unique orthogonal subspace decomposition
called *eigenspace decomposition*. Moreover, for every such decomposition,
there exists a Hermitian operator whose eigenspace decomposition is this
decomposition.

#theorem[
  Let $O: V -> V$ be an Hermitian operator in matrix form, having
  eigenvalues $lambda_(1), dots, lambda_(n)$. Let $S_(lambda_(i))$
  be the subspace generated by the $i$-th eigenvalue, and let
  $\{S_(lambda_(i))\}$ be the set that contains those subspaces.
  $\{S_(lambda_(i))\}$ is an orthogonal set and:

  $ S_(lambda_(1)) plus.circle S_(lambda_(2)) plus.circle dots
    plus.circle S_(lambda_(n)) = V $

  This decomposition is unique.
] <Eigenspace-decomposition>
#proof[
  First, note how two eigenspaces of a matrix are necessarely disjoint.
  Given a unit vector $bold(x)$ and two distinct eigenvalues $lambda_(1)$
  and $lambda_(2)$, if $O bold(x) = lambda_(1) bold(x)$ and $O bold(x) =
  lambda_(2) bold(x)$ then $lambda_(1) bold(x) = lambda_(2) bold(x)$, but
  this is only possible if $lambda_(1) = lambda_(2)$.

  For any Hermitian operator, the eigenvectors for distinct eigenvalues
  must be orthogonal. Let $bold(v)_(1)$ be an eigenvector for $lambda_(1)$
  and $bold(v)_(2)$ an eigenvector for $lambda_(2)$. Then:

  $ lambda_(1) angle.l bold(v)_(1), bold(v)_(2) angle.r =
    angle.l bold(v)_(1)^(*) O^(dagger), bold(v)_(2) angle.r =
    angle.l bold(v)_(1), O bold(v)_(2) angle.r =
    lambda_(2) angle.l bold(v)_(1), bold(v)_(2) angle.r $

  Since $lambda_(1)$ and $lambda_(2)$ were assumed to be distinct,
  $lambda_(1) angle.l bold(v)_(1), bold(v)_(2) angle.r = lambda_(2)
  angle.l bold(v)_(1), bold(v)_(2) angle.r$ is possible only if 
  $angle.l bold(v)_(1), bold(v)_(2) angle.r = 0$.

  // Prove that the decomposition is true
]
